platform :ios, '7.0'

link_with 'SoCal', 'SoCal-Dev'

pod 'AFNetworking', '~> 2.5.0s'
pod 'libPusher', '~> 1.5'
# pod 'AWSiOSSDK', '~> 1.7.1'
# pod 'SDWebImage'

workspace 'SoCal'

# ignore all warnings from all pods
inhibit_all_warnings!
